name: API report (misskey.js)

on:
  push:
    paths:
      - packages/fedired-js/**
      - .github/workflows/api-fedired-js.yml
  pull_request:
    paths:
      - packages/fedired-js/**
      - .github/workflows/api-fedired-js.yml
jobs:
  report:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm --filter fedired-js build

      - name: Check files
        run: ls packages/fedired-js/built

      - name: API report
        run: pnpm --filter fedired-js api-prod

      - name: Show report
        if: always()
        run: cat packages/fedired-js/temp/fedired-js.api.md
